# Generated by Django 4.2.6 on 2023-11-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
