version: '3.8'
services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    # command: 'python manage.py runserver 0.0.0.0:8000'
    command: 'gunicorn wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - ./app:/usr/src/app/
      - mediafiles:/usr/src/app/mediafiles
      - staticfiles:/usr/src/app/static

    ports:
      - '8000:8000'
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: 'postgres:15'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - staticfiles:/usr/src/app/static
      - mediafiles:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: null
  mediafiles: null
  staticfiles: null
