version: '3.8'

services:

  web:
    restart: unless-stopped
    build: 
      context: ./app
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.prod
    command: 
      # 'python manage.py runserver 0.0.0.0:8000'    # development
      'gunicorn wsgi:application --bind 0.0.0.0:8000'   # production
    volumes:
      - ./app:/usr/src/app/
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/mediafiles


    ports:
      - '8000:8000'
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: 'postgres:15'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
    env_file:
      - ./.env.prod.db

  nginx:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: null
  mediafiles: null
  staticfiles: null
